### ISSUE TITLE
bundle.js is not found

### ISSUE THREAD

**Issue by FredericBGA** [kiranbandi/synvisio#1]
Hello,

`bundle.js` is not found, and we then have a 404 error:
https://github.com/kiranbandi/synvisio/blob/06d8243682ea293aec900241429c8971d3955de2/build/index.html#L45
Can we safely change:  `src="/assets/bundle/bundle.js"` to ` src="assets/bundle/bundle.js"` and create a symbolic link from `main.bundle.b1712a00b208cba4aabd.js` to `bundle.js` ?

Thank you.

**Comment by kiranbandi** [comment]
Hi,
Thanks for showing interest in SynVisio. Could you be more specific on what you want to do with the generated bundle. 

The index.html file is generated dynamically by webpack during the build and is automatically updated with the randomized bundle name so you ideally dont need to update it. 

If you want the run the project locally. You can run `npm run start` and that should start the project at [localhost:8080](http:localhost:8080)

if you want a production ready build that you would like to host yourself on a different server.
you can run 'npm run build'. That should create a ready bundle for you inside the build folder which can then be hosted wherever you want. 

However if you are not familiar with webpack and NodeJS builds then you can simply download a copy of a readymade build available at [https://github.com/kiranbandi/synvisio/tree/gh-pages](https://github.com/kiranbandi/synvisio/tree/gh-pages) . That should have all the correct linkings. 

Kiran

**Comment by FredericBGA** [comment]
ok, perfect. Thank you. I will use the already build files (this commit `commit b17c4c58bf6d0f2ef52d675b4447a9c75a43b37b` was working with the build files that's why I used also these files with this last version).
I have some issues with npm (my dev server is quite old) so I failed to run the build so far.
