### ISSUE TITLE
Hi!Dr.kiranbandi  How to adjust the picture width

### ISSUE THREAD

**Issue by ChenXi1201** [kiranbandi/synvisio#10]
![image](https://user-images.githubusercontent.com/74816124/145323293-1250ed2d-f0ea-4db0-9db9-ace53984c876.png)
I have too many chromosomes to draw which led to many overlapping names.
After Press F12, I didn't find a place that effectively change the width. I want to make the picture wider
![image](https://user-images.githubusercontent.com/74816124/145323603-3c41a9dd-8685-49a7-a385-6aee93df0957.png)
This place can only change the width of the web page. It seems that it can't change the width of the picture
Can you tell me how to adjust the width of the picture?

**Comment by kiranbandi** [comment]
The width of the chart is dynamically set on page load based on the page width. Changing the width of the svg element after it has rendered will likely not do anything. 
If you are able to get the system up and running in your local. You can potentially override the width and height of the charts by hardcoding them in the following file - 
https://github.com/kiranbandi/synvisio/blob/master/src/utils/getPlotDimensions.js

As you can see the width of the chart is being set based on the window width on line 3. You can override this to a higher value if you want.
