### ISSUE TITLE
just a comment

### ISSUE THREAD

**Issue by dcourtine** [kiranbandi/synvisio#2]
Hello,

I find your tool very interesting, in particular the simultaneous global and local views of the synteny.

However, I have two remarks:
1. Help for beginners with a section "*Install*" in the documentation, as it is not trivial. 

I have a MacBook running MacOS 10.14.6. *Synvisio* is installed localy, within a Conda environment to keep all the JavaScript packages in the same place, avoiding conflicts with the ones installed on my system. First, clone the repo, cd and `npm install`. I had to fix some dependency errors. Then I start *Synviso* with `npm run start`, open `http://localhost:8080/` and it works perfectly 😄 .  
I haven't tried to install *Synvisio* globally (`/Library/WebServer/Documents` on MacOS) because I don't plan to use it on a daily basis.

2. Highlight genes not involved in the syntenic block.

At the very bottom of the dashboard, where we can see the details of the selected syntenic block (bottom of this [image](https://github.com/kiranbandi/synvisio/blob/master/build/assets/img/demo/3.png)), would it be possible for you to implement a function to display genes without a mate in the synenic block?  In my work, I am interested in syntenic genes, but it can also be interesting to take a look at genes without a mate within such conserved region! I hope I was clear 😄.  
To make it simple with an example: two genomes, one syntenic block., genes A and A'; C and C' are syntenic *mates*.

Genome1     ==AAAA====BB===CCCCCC=====  
. . . . . . . . . . .|||||||. . . . . . . . . . . ||||||||||||   
Genome2    ==A'A'A'==========C'C'C'C'C'====

Is it possible to highlight the gene *B* along the chromosome/scaffold in the bottom pannel of the *Synvisio* dashboard?

Your tool is really very pleasant and easy to use! The graphics are also nice and it is a strength to be able to directly insert a figure from *Synvisio* into a publication / presentation.
All the best for the future,

Damien

**Comment by kiranbandi** [comment]
Hi Damien,

Thanks a lot for your feedback on using the tool. I am glad that you found it pleasant and easy to use.
I am also sorry you had trouble installing the local version of the system and I'll update the readme file to be more descriptive. However, SynVisio is a web application that is free to use at [https://synvisio.github.io/](https://synvisio.github.io/). So ideally you don't need to install the system locally on your machine and can directly use the web application on your browser by visiting the above link. The local installation is only needed if you want to change the system for a different use case or add a feature that doesn't exist. But nonetheless, I'll update the readme file to make this more clear. 

For the second point, I am currently working on an update to also show the non-syntenic genes and regions along with the syntenic pairs so I'll let you know as soon as the feature is ready. And also yes I can add definitely add in a new feature that will let you highlight the genes that you need even if they don't belong to a syntenic pair. Thanks again for the descriptive feedback. 

My research area is in visualizing genomic information so we are currently working on an updated version of SynVisio with support for several new additional features such as visualizing synteny across pangenomes in combination with a phylogenetic tree. So we are always looking to add more features to the system based on feedback from genome researchers such as yourself. So please feel free to drop me a mail at venkat.bandi@usask.ca if you need any new feature in synvisio or are looking to visualize some genomic data in a particular way that isn't currently available.

Thanks again,
Kiran
