### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by fafuyyk** [kiranbandi/synvisio#20]
Hi, I'm finding a problem when using SynVisio to view my own collinearity results.
SynVisio does not recognize some chromosome names. I am very confused about this, I wonder if SynVisio has format requirements for chromosome names?

**Comment by kiranbandi** [comment]
SynVisio by default tags chromosomes that don't follow the standard chromosome naming pattern (two characters followed by number CHXX) as scaffolds and scaffolds are filtered out by default. If you think your chromosomes are being tagged as scaffolds and filtered out, you can select No to the question "Would you like to ignore Scaffold regions ?" in the upload page. This will ensure that they show up in the dashboard.

**Comment by fafuyyk** [comment]
Thanks for your reply, this is indeed the problem.
But I am using self-hosted-module now, and I am going to install synvisio into my personal database, so what configuration do I need to modify in this mode. Thanks for your help, I'll cite synvisio when I post.

**Comment by kiranbandi** [comment]
So the scaffold filtering happens in line 20 in the file gff.worker.js based on the value of the flag **processScaffolds** as shown below - 
https://github.com/kiranbandi/synvisio/blob/9422ec2216304bdb6274c22d9af78e2128ad8bca/src/workers/gff.worker.js#L20

As you can see the default value for the flag **processScaffolds** is set to false in line 6. 
https://github.com/kiranbandi/synvisio/blob/9422ec2216304bdb6274c22d9af78e2128ad8bca/src/workers/gff.worker.js#L6
You can either set this to true in line 6, or you can remove the check on line 20 to bypass scaffold filtering. 

A more straightforward way of fixing the issue without changing anything in the code, would be to edit your gff file so that chromosomes are following the standard "CHXX" naming pattern where CH is the 2 character chromosome label and XX are the chromosome numbers.

**Comment by fafuyyk** [comment]
Sorry to bother you again, I tried the method you gave me on self-hosted-module, modified the script and chromosome names. I changed Dla1 to DA1, but it didn't work. The interesting thing is that when I changed my chromosome name from Dla1 to ath1, the chromosome name can be displayed, but ath also does not meet the standard naming. And I changed Dla1 to become unavailable again when the number after ath becomes 2 digits. I think it's probably not just a scafford filtering issue

**Comment by kiranbandi** [comment]
That sounds strange. If you have disabled scaffolding it shouldnt matter what your chromosome names are. Could you drop me a mail at venkat.bandi@usask.ca with a sample of your input files. I can test them on my local system and let you know what the problem is.

**Comment by fafuyyk** [comment]
Thanks for your reply, my problem has been solved, the problem seems to be because `npm run build` is not running, I have solved the problem. I would like to ask you one last question, how can I set the default Chart Configuration. And I want users to see the collinear image directly when they open the web page, instead of having to adjust the Chart Configuration and click the GO button. I am very grateful for your help.

**Comment by fafuyyk** [comment]
Thanks for your reply, my problem has been solved, the problem seems to be because `npm run build` is not running, I have solved the problem. I would like to ask you one last question, how can I set the default Chart Configuration. And I want users to see the collinear image directly when they open the web page, instead of having to adjust the Chart Configuration and click the GO button. I think there should be a config file, but I haven't found it yet. Looking forward to your reply!

**Comment by fafuyyk** [comment]
Thanks for your reply, my problem has been solved, the problem seems to be because `npm run build` is not running, I have solved the problem. I would like to ask you one last question, how can I set the default Chart Configuration. And I want users to see the collinear image directly when they open the web page, instead of having to adjust the Chart Configuration and click the GO button. I think there should be a config file, but I haven't found it yet. Looking forward to your reply!

**Comment by fafuyyk** [comment]
Thanks for your reply, my problem has been solved, the problem seems to be because `npm run build` is not running, I have solved the problem. But I have one last question, how can I set the default Chart Configuration. And I want users to see the collinear image directly when they open the web page, instead of having to adjust the Chart Configuration and click the GO button. I think there should be a config file, but I haven't found it yet. Thank you for your help.

**Comment by kiranbandi** [comment]
Yeah if you are trying to make changes and testing them out you should be running "npm run start" which will create a local server that updates on file change. Once you are satisfied with your results running "npm run build" gives you a production version of the codebase. The readme file already has documentation on how the set the default source and target chromosomes but beyond that there is no easy way to modify the default chart configurations. If you would like to make changes to them you will have to experiment by modifying the default values in the file - https://github.com/kiranbandi/synvisio/blob/master/src/redux/reducers/initialState.jsx".

Also users will have to click on the go button for the chart to load. If you want to experiment with it, you can try clicking the button through javascript after the page and the data files have loaded but you will have to make sure to not trigger the button before the file processing is not complete.

**Comment by fafuyyk** [comment]
Thank you very much for your reply, I understand how to do it ！
