### ISSUE TITLE
Trouble with Hive View

### ISSUE THREAD

**Issue by cassondranewman** [kiranbandi/synvisio#21]
Hello, 
Thank you for this visualization tool! I have a comparison between three genomes. I have successfully used your tool for multi level analysis with the 3D Cube View. Then, when I try to use the multi level analysis with the Hive View I cannot make any chart. It does not even allow me to select the chromosomes I want to compare (like the 3D view allows you to do). How can I get the hive view to populate?

**Comment by kiranbandi** [comment]
Hi there, 
For the hive and the tree view you first need to add the chromosome selectors by clicking on the "+" button. So for example if you want to have a 3 way comparison, you need to click it thrice and that will create three selection dropdowns on the screen. Then you can select the chromosomes from the dropdown and hit GO. The tree also works in a similar way. Unlike the 3D Cube view which is limited to 3 way comparisions you can compare "N" different levels in these other views hence the ability to add/remove as many chromsome levels as you want. Hope that makes sense. 

Sorry its not documented well.

**Comment by cassondranewman** [comment]
Amazing! Thanks for the clarification!

**Comment by cassondranewman** [comment]
Wow nice! Thank you for pointing me to these additional tools!
