### ISSUE TITLE
How to specify min and max values in bedgraph files?

### ISSUE THREAD

**Issue by shelkmike** [kiranbandi/synvisio#28]
SynVisio works correctly when the header of a bedgraph file is
`track type=bedGraph`

However, if I want to indicate custom minimum and maximum values, SynVisio doesn't show the tracks.
I tried the following variants:
`track type=bedGraph min=0,max=1`
`track type=bedGraph min=0 max=1`
`track type=bedGraph "min=0,max=1"`

How should minimum and maximum values be specified in the header line?

**Comment by kiranbandi** [comment]
You dont need the track type in the header. It is already implied that only bedgraph files will be used in the upload. 
You can just have the first line in the file be - 
min=0,max=1

**Comment by shelkmike** [comment]
Thank you, this helped
