### ISSUE TITLE
can not open the link of "https://synvisio.github.io."

### ISSUE THREAD

**Issue by jigaoxiang** [kiranbandi/synvisio#5]
Hi
I can not open the link of  SynVisio using https://synvisio.github.io. And i try to use 
`git clone https://github.com/kiranbandi/synvisio.git` 
to clone the file,the below is all the file in my synvisio
`build  build-config  deploy.sh  LICENSE  package.json  package-lock.json  README.md  src `
But  I can not find any executable file, and the link of https://synvisio.github.io.  and https://openreview.net/pdf?id=7-C5VJWbnI can not open. May be some firewall in my Internet. Could you please send the software and documention in zip or gzip or other way to my email 923185578@qq.com? Thank you very much!

**Comment by kiranbandi** [comment]
Hi there,

There are 2 other mirrored versions of synvisio at the following links can you see if you can access any of them - 
https://kiranbandi.github.io/synvisio
https://synvisio.usask.ca

If not the best thing to do would be to run your own local server, 
to do this you must first install nodejs.

Then after cloning the project run the following commands - 

Install dependencies,
```bash
$ npm install
```
Start local server
```bash
$ npm run start
```
The local version of synvisio should be available at [http://localhost:8080/](http://localhost:8080/)

**Comment by jigaoxiang** [comment]
Thank you very much! The second link can open easy!
